### ISSUE TITLE
Need to be able to change Legend size as well as the color on the Taylor diagrams

### ISSUE THREAD

**Issue by yousef1983** [PeterRochford/SkillMetrics#26]
I am running taylor_diagram_ex10.py but I am not happy with the legend size. Can you please help in adjusting the legend size and location? how can I change the marker color for each of them?

![image](https://user-images.githubusercontent.com/47751959/141961193-74a50cba-164e-4bf5-9c52-c76ae0456ec2.png)

Thanks!

**Comment by PeterRochford** [comment]
I have added a 'markers" option to the SkillMetrics package in version 1.2.2 that I hope to release soon. This allows the user to individually control of the marker label, label color, symbol, size, face color, and edge color via specifications given via a dictionary. Refer to the examples [Target 11](https://github.com/PeterRochford/SkillMetrics/wiki/Examples:-Target-Diagrams#target-diagram-example-11) and [Taylor 15](https://github.com/PeterRochford/SkillMetrics/wiki/Examples:-Taylor-Diagrams#taylor-diagram-example-15).  

This will meet your need to change the color and shape of the markers. How to change the size of the legend remains an outstanding issue. The cleaner way to accomplish this would be within the main script using legend handles that are returned with the diagram rather than a custom feature of the SkillMetrics package. I will add this to the To Do list as a [FAQ](https://github.com/PeterRochford/SkillMetrics/wiki/FAQ) after releasing SkillMetrics 1.2.2 via pip.

**Comment by PeterRochford** [comment]
I have added to the [FAQ](https://github.com/PeterRochford/SkillMetrics/wiki/FAQ) under the [Plotting Issues](https://github.com/PeterRochford/SkillMetrics/wiki/FAQ#plotting-issues) section a new Q13 on how to adjust the legend size and other properties. However, the SkillMetrics package as currently designed does not allow you to control the legend location.

**Comment by PeterRochford** [comment]
SkillMetrics 1.2.2 is now available.
